name: Build release

on:
  workflow_dispatch:

jobs:
  build_kernel:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [ksu, next, clean, sukisu]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt-get remove --purge -y "php*" "dotnet*" "mysql*" "clang*" "google*"
          sudo apt autoremove -y
          sudo apt install -yq tar \
            attr libelf-dev dwarves rsync libbrotli-dev \
            libgtest-dev libprotobuf-dev libunwind-dev libusb-1.0-0-dev libzstd-dev libc6-dev \
            linux-modules-extra-$(uname -r) build-essential p7zip-full libarchive-tools cpio
          
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch ToolChain
        run: |
          mkdir -p ~/Prebuilts
          mkdir -p ~/Prebuilts/clang-r547379
          wget -c https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/llvm-r547379-release/clang-r547379.tar.gz -O clang.tar.gz
          tar -xf clang.tar.gz -C ~/Prebuilts/clang-r547379
          rm clang.tar.gz

      - name: Fetch AnyKernel3
        run: |
          git clone --branch gauguin https://github.com/Vaz15k/AnyKernel3.git ~/AnyKernel3
          mkdir -p ~/files

      - name: Set date variable
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV      

      - name: Build Kernel Clean
        if: matrix.target == 'clean'
        run: |
          ./build_kernel.sh --clean
          cp ~/AnyKernel3/gauguin* ~/files

      - name: Build Kernel With KSU
        if: matrix.target == 'ksu'
        run: |
          ./build_kernel.sh --ksu --clean
          cp ~/AnyKernel3/gauguin* ~/files

      - name: Build Kernel With KSU-NEXT
        if: matrix.target == 'next'
        run: |
          ./build_kernel.sh --next --clean
          cp ~/AnyKernel3/gauguin* ~/files

      - name: Build Kernel With SukiSU
        if: matrix.target == 'sukisu'
        run: |
          ./build_kernel.sh --sukisu --clean
          cp ~/AnyKernel3/gauguin* ~/files

      - name: Publish to GitHub
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files: /home/runner/files/*
          name: Gauguin Kernel - ${{ env.DATE }}
          tag_name: "${{ env.DATE }}"
          body: |
            ## Managers
            - **KernelSU-SusFS:** https://github.com/rsuntk/KernelSU/releases
            - **KernelSU-Next:** https://github.com/KernelSU-Next/KernelSU-Next/releases
            - **SukiSU:** https://github.com/SukiSU-Ultra/SukiSU-Ultra/releases
            
            ### Info
            
            SukiSU have support for KPM and SusFS. <br>
            KernelSU have support for SusFS. <br>
            KernelSU-Next susfs is disabled for now... <br>
            
            ---
            - **Kernel Version:** 4.19
            - **Clang Version:** Clang-r547379 
            :rocket: *Built with love by GitHub Actions.*
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
